/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasketiga;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class framepajak extends javax.swing.JFrame {
    double Pajak;
    int Gaji, Kendaraan;

    /**
     * Creates new form framepertama
     */
    public framepajak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eHeader = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        gaji = new javax.swing.JLabel();
        kendaraan = new javax.swing.JLabel();
        pajak = new javax.swing.JLabel();
        eGaji = new javax.swing.JTextField();
        eKendaraan = new javax.swing.JTextField();
        ePajak = new javax.swing.JTextField();
        eHitung = new javax.swing.JButton();
        eTampilkan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        eHeader.setEditable(false);
        eHeader.setFont(new java.awt.Font("Felix Titling", 0, 18)); // NOI18N
        eHeader.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eHeader.setText("PERHITUNGAN PAJAK SEDERHANA");
        jPanel1.add(eHeader, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gaji.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gaji.setText("GAJI");
        jPanel3.add(gaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, -1, -1));

        kendaraan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kendaraan.setText("KENDARAAN");
        jPanel3.add(kendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, -1, -1));

        pajak.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pajak.setText("PAJAK");
        jPanel3.add(pajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, -1));

        eGaji.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(eGaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 14, 234, -1));

        eKendaraan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(eKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 40, 234, -1));

        ePajak.setEditable(false);
        ePajak.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(ePajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 91, 231, -1));

        eHitung.setFont(new java.awt.Font("STCaiyun", 1, 12)); // NOI18N
        eHitung.setText("HITUNG");
        eHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eHitungActionPerformed(evt);
            }
        });
        jPanel3.add(eHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 66, -1, -1));

        eTampilkan.setFont(new java.awt.Font("STCaiyun", 1, 12)); // NOI18N
        eTampilkan.setText("TAMPILKAN");
        eTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTampilkanActionPerformed(evt);
            }
        });
        jPanel3.add(eTampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasketiga/bg2.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 370, 170));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eHitungActionPerformed
        Gaji = Integer.parseInt(eGaji.getText());
        Kendaraan = Integer.parseInt(eKendaraan.getText());
        
        if (Gaji >= 10000000 && Kendaraan >= 3){
            Pajak = Gaji * 15/100;
        }else if(Gaji >= 5000000 && Kendaraan >= 2){
            Pajak = Gaji * 10/100;
        }else if(Gaji >= 5000000 && Kendaraan >= 1){
            Pajak = Gaji * 7/100;
        }else if(Gaji < 5000000 && Kendaraan >= 1){
            Pajak = Gaji * 5/100;
        }else if(Gaji <5000000 && Kendaraan >= 0){
            Pajak = Gaji * 2.5/100;
        }
        ePajak.setText(Double.toString(Pajak));
    }//GEN-LAST:event_eHitungActionPerformed

    private void eTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTampilkanActionPerformed
        Gaji = Integer.parseInt(eGaji.getText());
        Kendaraan = Integer.parseInt(eKendaraan.getText());
        
        JOptionPane.showMessageDialog(this,
            "GAJI          : " + Gaji +
            "\nKENDARAAN   : " + Kendaraan+
            "\nPAJAK       : Rp. " + Pajak);
        
        eGaji.setText("");
        eKendaraan.setText("");
        ePajak.setText("");
    }//GEN-LAST:event_eTampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framepajak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framepajak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framepajak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framepajak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framepajak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eGaji;
    private javax.swing.JTextField eHeader;
    private javax.swing.JButton eHitung;
    private javax.swing.JTextField eKendaraan;
    private javax.swing.JTextField ePajak;
    private javax.swing.JButton eTampilkan;
    private javax.swing.JLabel gaji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel kendaraan;
    private javax.swing.JLabel pajak;
    // End of variables declaration//GEN-END:variables
}
