/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasketiga;

/**
 *
 * @author ASUS
 */
public class frameperpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form frameperpustakaan
     */
    public frameperpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eHeader = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        eBuku1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eBuku2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        eBuku3 = new javax.swing.JLabel();
        Btn3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        eJudul = new javax.swing.JLabel();
        penulis = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        tentang = new javax.swing.JLabel();
        ePenulis = new javax.swing.JTextField();
        ePenerbit = new javax.swing.JTextField();
        eJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eTentang = new javax.swing.JTextArea();
        eTahun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        eHeader.setBackground(new java.awt.Color(0, 0, 0));
        eHeader.setFont(new java.awt.Font("Euphorigenic", 1, 36)); // NOI18N
        eHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eHeader.setText("PERPUSTAKAAN SEDERHANA");
        jPanel1.add(eHeader, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        eBuku1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eBuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasketiga/bK1.jpg"))); // NOI18N

        jLabel5.setText("-----------------");

        eBuku2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eBuku2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasketiga/bk2.jpg"))); // NOI18N

        jLabel7.setText("-----------------");

        Btn1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Btn1.setText("DETAIL");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Btn2.setText("DETAIL");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        eBuku3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eBuku3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasketiga/bk3.jpg"))); // NOI18N

        Btn3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Btn3.setText("DETAIL");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eBuku2)
                    .addComponent(eBuku1)
                    .addComponent(eBuku3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(eBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eBuku2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eBuku3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eJudul.setFont(new java.awt.Font("FZShuTi", 1, 36)); // NOI18N
        eJudul.setText("JUDUL BUKU");
        jPanel3.add(eJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 6, -1, -1));

        penulis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        penulis.setText("PENULIS");
        jPanel3.add(penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 263, -1, -1));

        penerbit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        penerbit.setText("PENERBIT");
        jPanel3.add(penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, -1, -1));

        tahun.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tahun.setText("TAHUN TERBIT");
        jPanel3.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, -1, -1));

        jumlah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jumlah.setText("JUMLAH HALAMAN");
        jPanel3.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 383, -1, -1));

        tentang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tentang.setText("TENTANG BUKU");
        jPanel3.add(tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 57, -1, -1));

        ePenulis.setEditable(false);
        ePenulis.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(ePenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 259, 242, 34));

        ePenerbit.setEditable(false);
        ePenerbit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ePenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePenerbitActionPerformed(evt);
            }
        });
        jPanel3.add(ePenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 299, 242, 34));

        eJumlah.setEditable(false);
        eJumlah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        eJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJumlahActionPerformed(evt);
            }
        });
        jPanel3.add(eJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 379, 242, 35));

        eTentang.setEditable(false);
        eTentang.setColumns(20);
        eTentang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        eTentang.setRows(5);
        jScrollPane1.setViewportView(eTentang);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 426, 170));

        eTahun.setEditable(false);
        eTahun.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        eTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTahunActionPerformed(evt);
            }
        });
        jPanel3.add(eTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 339, 242, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasketiga/bg1.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 450, 460));

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ePenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePenerbitActionPerformed

    private void eJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eJumlahActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        eJudul.setText("Laskar Pelangi");
        ePenulis.setText("Andrea Hirata");
        ePenerbit.setText("Bentang Pustaka");
        eTahun.setText("2005");
        eJumlah.setText("529 Halaman");
        eTentang.setText("Novel Laskar Pelangi menceritakan kehidupan 10 anak yang tidak mampu,"
                + "\ntetapi memiliki semangat juang untuk melanjutkan pendidikannya di kampung Gantung,"
                + "\nKepulauan Bangka Belitung.Sebagian besar dari kesepuluh anak yang menempuh pendidikan "
                + "\ndi SD Muhammadiyah Gantung,merupakan anak dari para penambang timah di pulau "
                + "\ndengan perolehan kekayaan alam timah yang terbesar di dunia."
                + "\nMeski demikian, hal tersebut berbanding terbalik dengan taraf kesejahteraan masyarakat asli di suatu daerah. "
                + "\nRealitas itu yang mesti diterima oleh seluruh kalangan, mulai dari anak-anak, para orang tuanya, "
                + "\nbahkan masyarakat miskin di daerah setempat");        
    }//GEN-LAST:event_Btn1ActionPerformed

    private void eTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTahunActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        eJudul.setText("Bumi Tere Liye");
        ePenulis.setText("Tere Liye");
        ePenerbit.setText("Gramedia Pustaka Utama");
        eTahun.setText("2014");
        eJumlah.setText("440 Halaman");
        eTentang.setText("Novel Bumi karya Tere Liye berkisah mengenai petualangan antar klan dengan tokoh utamanya, yaitu Raib."
                + "\nRaib adalah generasi keturunan murni dari Klan Bulan dan ia melakukan petualangan ke dunia paralel "
                + "\nbersama dua sahabatnya, yaitu Seli dan Ali.Seli berasal dari keturunan klan Matahari, "
                + "\nsementara Ali berasal dari klan Bumi atau tanah.Sebenarnya, mereka bertiga "
                + "\nmerupakan anak remaja pada umumnya, tetapi di novel inilah awal dari segalanya terungkap"
                + "\nMeskipun alur novel Bumi mengangkat tentang petualangan di dunia paralel, "
                + "\ntetapi Tere Liye menyampaikan begitu banyak pesan. "
                + "Seperti makna persahabatan, niat tulus membantu terhadap sesama dan berbagai kebaikan lainny\n");
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        eJudul.setText("Laut Bercerita");
        ePenulis.setText("Leila S. Chudori");
        ePenerbit.setText("Kepustakaan Populer Gramedia");
        eTahun.setText("2017");
        eJumlah.setText("379 Halaman");
        eTentang.setText("Novel LAut BErcerita Laut Bercerita menceritakan terkait perilaku kekejaman "
                + "dan kebengisan yang dirasakan oleh kelompok aktivis mahasiswa di masa Orde Baru."
                + "\nTidak hanya itu, novel ini pun merenungkan kembali akan hilangnya 13 aktivis,"
                + "\nbahkan sampai saat ini belum juga ada yang mendapatkan petunjuknya."
                + "\nCerita dalam novel Laut Bercerita terbagi menjadi dua bagian dengan jarak waktu yang jauh berbeda."
                + "\nAdapun bagian pertama diceritakan melalui sudut pandang tokoh bernama "
                + "\nBiru Laut beserta para kawan sesama aktivisnya seraya menyelesaikan visi atau tujuan mereka. "
                + "\nSementara pada bagian kedua, kisahnya diambil dari sudut pandang Asmara Jati, "
                + "\nadik dari Laut yang mempunyai tujuan atau visi yang cenderung berlainan dengan Laut.");
    }//GEN-LAST:event_Btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameperpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameperpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameperpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameperpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameperpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JLabel eBuku1;
    private javax.swing.JLabel eBuku2;
    private javax.swing.JLabel eBuku3;
    private javax.swing.JLabel eHeader;
    private javax.swing.JLabel eJudul;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JTextField ePenerbit;
    private javax.swing.JTextField ePenulis;
    private javax.swing.JTextField eTahun;
    private javax.swing.JTextArea eTentang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel penulis;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel tentang;
    // End of variables declaration//GEN-END:variables
}
